export { default as auth } from '@/store/modules/auth'
export { default as color } from '@/store/modules/color'
export { default as gradient } from '@/store/modules/gradient'
export { default as palette } from '@/store/modules/palette'
export { default as workspace } from '@/store/modules/workspace'
